### ISSUE TITLE
[high] check ACT Rules links for all

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#174] opened 2024-02-02 01:17 UTC
e.g., IBM Equal Access Accessibility Checker (Chrome, Firefox, Edge extension) has:
```<a href="https://www.w3.org/WAI/standards-guidelines/act/implementations/https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/" target="_blank">ACT Rules implemented</a>:```

**Comment by iadawn** [comment] 2024-02-02 11:37
Duplicate of #169

**Closed by iadawn** 2024-02-02 11:37 UTC
